clear errno before calling ptrace()
binding: clear errno before calling `ptrace()` as mandated by the
manual page.

According to the manual page it is valid to return `-1` using `PTRACE_PEEK_*`
commands, leaving errno intact. For that reason it is necessary to clear
`errno` before calling `ptrace()`.

In order to do that we need to use `ctypes.CDDL()` with `use_errno`
together with `ctypes.get_errno()` and `ctypes.set_errno()`[2] at least
when cptrace is not being used which seems to be the default.

The bug was found when running network-testing[1] and it caused the
following traceback:

    Traceback (most recent call last):
      File "./test-client-server", line 5, in <module>
        main()
      File "/home/pavlix/oss/network-testing/network_testing/client_server.py", line 55, in main
        suite.run()
      File "/home/pavlix/oss/network-testing/network_testing/test_suite.py", line 431, in run
        testcase.run()
      File "/home/pavlix/oss/network-testing/network_testing/test_suite.py", line 391, in run
        scenario.run()
      File "/home/pavlix/oss/network-testing/network_testing/test_suite.py", line 172, in run
        debugger.quit()
      File "/home/pavlix/oss/network-testing/network_testing/debug.py", line 198, in quit
        super(SyscallDebugger, self).quit()
      File "/usr/lib64/python3.4/site-packages/ptrace/debugger/debugger.py", line 105, in quit
        process.terminate()
      File "/usr/lib64/python3.4/site-packages/ptrace/debugger/process.py", line 330, in terminate
        self.waitExit()
      File "/usr/lib64/python3.4/site-packages/ptrace/debugger/process.py", line 351, in waitExit
        self.cont(signum)
      File "/usr/lib64/python3.4/site-packages/ptrace/debugger/process.py", line 717, in cont
        ptrace_cont(self.pid, signum)
      File "/usr/lib64/python3.4/site-packages/ptrace/binding/func.py", line 212, in ptrace_cont
        ptrace(PTRACE_CONT, pid, 0, signum)
      File "/usr/lib64/python3.4/site-packages/ptrace/binding/func.py", line 148, in ptrace
        raise PtraceError(message, errno=errno, pid=pid)
    ptrace.error.PtraceError: ptrace(cmd=7, pid=6476, 0, 133) error #3: No such process

[1]: https://github.com/pavlix/network-testing
[2]: https://docs.python.org/2/library/ctypes.html